### ISSUE TITLE
uncaught at t TypeError: Cannot read property '_currentElement' of null

### ISSUE THREAD

**Issue by Phocea** [MhdSyrwan/aor-embedded-array#3]
Hello,

I am getting the following stack trace error when using `EmbeddedArrayInput` one inside another one

My JSON payload look like:
```
{"id":"stcuEchLoadid_9",
"name":"Channel name",
"metadataSet":[{"locale":"en_GB","metadata":[{"key":"Title","value":"channel 01 title"}]},
               {"locale":"none","metadata":[{"key":"another key","value":"another value"},
                                            {"key":"a key","value":"a value"},
                                            {"key":"Rating","value":"1"}
                                           ]
               }]}
```

and my JSX like:

```
    <Edit title={<ChannelTitle />} {...props}>
      <SimpleForm>
        <DisabledInput source="id"/>
        <TextField source="name" validate={required}/>
        <EmbeddedArrayInput source="metadataSet">
           <TextField source="locale" />
             <EmbeddedArrayInput source="metadataSet">
               <TextField source="key" />
               <TextField source="value" />
             </EmbeddedArrayInput>
        </EmbeddedArrayInput>
      </SimpleForm>
    </Edit>
```

The full stack trace if it helps

> uncaught at t TypeError: Cannot read property '_currentElement' of null
>     at f._updateRenderedComponent (http://localhost:8080/OpUi/static/js/main.4446f59a.js:1:481451)
>     at f._performComponentUpdate (http://localhost:8080/OpUi/static/js/main.4446f59a.js:1:481276)
>     at f.updateComponent (http://localhost:8080/OpUi/static/js/main.4446f59a.js:1:480553)
>     at f.receiveComponent (http://localhost:8080/OpUi/static/js/main.4446f59a.js:1:479670)
>     at Object.receiveComponent (http://localhost:8080/OpUi/static/js/main.4446f59a.js:1:88310)
>     at Object.obj.(anonymous function) [as receiveComponent] (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/backend.js:8598:20)
>     at Object.updateChildren (http://localhost:8080/OpUi/static/js/main.4446f59a.js:1:474763)
>     at m._reconcilerUpdateChildren (http://localhost:8080/OpUi/static/js/main.4446f59a.js:1:472620)
>     at m._updateChildren (http://localhost:8080/OpUi/static/js/main.4446f59a.js:1:473369)
>     at m.updateChildren (http://localhost:8080/OpUi/static/js/main.4446f59a.js:1:473267)
> f @ utils.js:225
> (anonymous) @ proc.js:483
> r @ scheduler.js:19
> u @ scheduler.js:60
> o @ scheduler.js:33
> T @ proc.js:476
> _ @ proc.js:425
> h @ proc.js:306
> n @ proc.js:378
> Promise resolved (async)
> E @ proc.js:440
> S @ proc.js:507
> _ @ proc.js:425
> h @ proc.js:306
> n @ proc.js:378
> r @ proc.js:602
> t @ proc.js:617
> n @ proc.js:378
> (anonymous) @ proc.js:489
> r @ scheduler.js:19
> u @ scheduler.js:60
> o @ scheduler.js:33
> (anonymous) @ channel.js:185
> t @ channel.js:26
> (anonymous) @ middleware.js:67
> (anonymous) @ bindActionCreators.js:3
> value @ Edit.js:125
> value @ Edit.js:91
> e.notifyAll @ CallbackQueue.js:74
> close @ ReactReconcileTransaction.js:78
> closeAll @ Transaction.js:207
> perform @ Transaction.js:154
> perform @ Transaction.js:141
> perform @ ReactUpdates.js:87
> x @ ReactUpdates.js:170
> closeAll @ Transaction.js:207
> perform @ Transaction.js:154
> batchedUpdates @ ReactDefaultBatchingStrategy.js:60
> a @ ReactUpdates.js:95
> dispatchEvent @ ReactEventListener.js:145

its followed by a React Error `Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.`

**Comment by Phocea** [comment]
forget it... I was using `<TextField>` instead of `<TextInput>` on an  `<Edit>` view !
